[package]
name = "a64_doctestfail"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon-core = { version = "1.9.1", path = "rayon-core/" }

# add3 = "4.0"

[profile.release]
lto = true
